# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dacapo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench1', models.CharField(max_length=50)),
                ('bench_date', models.DateTimeField(verbose_name='date of benchmark')),
            ],
        ),
        migrations.CreateModel(
            name='Specjvm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench1', models.CharField(max_length=50)),
                ('bench2', models.CharField(max_length=50)),
                ('bench_date', models.DateTimeField(verbose_name='date of benchmark')),
            ],
        ),
    ]
