# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dacapo',
            old_name='pub_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='specjvm',
            old_name='pub_date',
            new_name='timestamp',
        ),
    ]
