# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specjvm',
            name='bench1',
        ),
        migrations.RemoveField(
            model_name='specjvm',
            name='bench2',
        ),
        migrations.AddField(
            model_name='specjvm',
            name='compiler',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='specjvm',
            name='compress',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='specjvm',
            name='crypto',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='specjvm',
            name='derby',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='specjvm',
            name='mpegaudio',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='specjvm',
            name='scimark',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='specjvm',
            name='serial',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='specjvm',
            name='startup',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='specjvm',
            name='sunflow',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AddField(
            model_name='specjvm',
            name='xml',
            field=models.CharField(default='-1', max_length=50),
        ),
    ]
