# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dacapo',
            name='details',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='specjvm',
            name='details',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
