# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_auto_20180628_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='n/a', max_length=50, unique=True),
        ),
    ]
